### ISSUE TITLE
Tracking issue for current refactoring efforts

### ISSUE THREAD

**Issue by regexident** [mackwic/rspec#29]
### Environment:

- [x] [Implementing `let` (or some kind of state for tests)](https://github.com/mackwic/rspec/issues/7) (WIP on [`environment` branch](https://github.com/mackwic/rspec/tree/environment))

### Before & After
- [x] [Implement `before_all` and `after_all`](https://github.com/mackwic/rspec/issues/20) (WIP)
- [x] [Real `before_each` and `after_each`](https://github.com/mackwic/rspec/issues/8) (WIP)

### Runner
- [ ] [Simplify formatter instantiation and runner attachement?](https://github.com/mackwic/rspec/issues/22)
- [ ] [`context::rdescribe` should use the `Simple` formatter](https://github.com/mackwic/rspec/issues/21)

### Timing
- [ ] [Test timeout](https://github.com/mackwic/rspec/issues/12)
- [ ] [timing the tests](https://github.com/mackwic/rspec/issues/11)
- [ ] [Timing the test suite](https://github.com/mackwic/rspec/issues/10)

### Filtering & Focussing
- [ ] [Skipped tests and describes](https://github.com/mackwic/rspec/issues/18)
- [ ] [Focused tests and describes](https://github.com/mackwic/rspec/issues/17)

### Async
- [ ] [Async tests](https://github.com/mackwic/rspec/issues/19)

### DSL
- [ ] [Get rid of `ctx` in `ctx.it()`](https://github.com/mackwic/rspec/issues/4)

**Comment by regexident** [comment]
# Environment 

I have a working implementation of safe environments (state, let, however you wanna call it).
You can check it out on its feature branch: `environment`.

The runner keeps a stack of environments (corresponding to the current path of contexts at a given time) and provides mutable access to the topmost environment during a context's closure execution.

Prior to descending to one of its sub-contexts (via `ctx.context`, `ctx.specify`, `ctx.when`) it then clones the topmost (i.e. current) environment's current state, pushes it onto the stack and provides access to it to the given sub-context. Upon leaving a context the topmost stack gets popped again, accordingly.

This allows for ease of use while providing full test isolation and exclusive mutability, thus opening up possibilities of fully concurrent yet thread-safe test execution.

In cases where cloning the environment is expensive it is advised to wrap the expensive value into a `Rc` and access it through `.make_mut()` when mutating, triggering clone-on-write.

**Comment by regexident** [comment]
# Before & After

I further more have a working implementation of `before_all`, `after_all`, `before_each` and `after_each` on a local branch, that I will publish once matured.

**Right now these closures are only applied to the context's environment they were assigned to.** Sub-contexts inherit a clone of their parent's environment, but a parent's `before_each` (e.g.) does not get called again for any of its sub-contexts. So one would have to define the `before_each` at the same level of the `ctx.then` it's supposed to be run before, not somewhere further up.
If one however needed such a behavior one could easily move the given block of code into an inline-function and simply call it from wherever, thereby avoiding having to type it redundantly.

**I'm also wondering if it's really worth providing support for multiple `before_all`, `after_all`, `before_each` and `after_each` per context**? If you have the need to split up your `before_` logic into multiple `before_`s, then you're probably trying to do too much within a single context/test to begin with. It's not so much about reducing complexity by allowing for only one each block per context for me but more about steering the framework's usage.

Any opinion on this, @mackwic?

**Comment by mackwic** [comment]
What about a tracking issue of the macros we would want to add ?

It's really time we add macros everywhere to make the interface more friendly, don't you think ?

**Comment by regexident** [comment]
Well, I do have both `before_all`/`after_all` and `before_each`/`after_each` working on a local branch of mine. :wink:

They only differ from https://github.com/mackwic/rspec/issues/20 and https://github.com/mackwic/rspec/issues/8 in that they only get applied to the blocks of their immediate contexts. But I don't see any downside of this personally. Hence me asking.

---

So given a test suite like this (this code actually works already):

<details>

```rust
extern crate rspec;

use std::io;
use std::collections::BTreeSet;

pub fn main() {
    let stdout = &mut io::stdout();
    let mut formatter = rspec::formatter::Simple::new(stdout);

    let env: BTreeSet<usize> = BTreeSet::new();

    /*
    For more complex setups one would usually want
    to make use of a wrapper Environment struct:
    
    #[derive(Clone, Debug)]
    struct Environment {
        set: BTreeSet<usize>,
    }

    let env = Environment {
        set: BTreeSet::new(),
    };
    */
    
    let mut runner = rspec::given("a BTreeSet", env, |ctx| {
        ctx.when("not having added any items", |ctx| {
            // 0
            ctx.then("it is empty", |env| {
                assert_eq!(env.is_empty(), true);
            });

            // 1
            ctx.then("its len is zero", |env| {
                assert_eq!(env.len(), 0);
            });

            // 2
            ctx.when("adding an item", |ctx| {
                // 2.0
                ctx.before_all(|env| {
                    env.insert(42);
                });

                // 2.1
                ctx.then("it is not empty anymore", |env| {
                    assert_eq!(env.is_empty(), false);
                });

                // 2.2
                ctx.then("its len is one", |env| {
                    assert_eq!(env.len(), 1);
                });

                // 2.3
                ctx.when("removing an item", |ctx| {
                    // 2.3.0
                    ctx.before_each(|env| {
                        env.remove(42);
                    });
                    
                    // 2.3.1
                    ctx.then("it is empty again", |env| {
                        assert_eq!(env.is_empty(), true);
                    });

                    // 2.3.2
                    ctx.then("its len is zero again", |env| {
                        assert_eq!(env.len(), 0);
                    });
                });
            });
        });
    });

    runner.add_event_handler(&mut formatter);
    runner.run_or_exit();
}
```

</details>

---

Then this is how the environment would change during execution:

<details>

```rust
"a BTreeSet":
    env: {}
    "not having added any items":
        env: {}
        "it is empty":
            env: {}
            assert_eq!(env.set.is_empty(), true);
        "its len is zero":
            env: {}
            assert_eq!(env.set.len(), 0);
        "adding an item":
            env: {}
            before_all
            env: {42}
            "it is not empty anymore"
                env: {42}
                assert_eq!(env.set.is_empty(), false);
            "its len is one"
                env: {42}
                assert_eq!(env.set.len(), 1);
            "removing an item"
                env: {42}
                "it is empty again":
                    env: {42}
                    before_each
                    env: {}
                    assert_eq!(env.set.is_empty(), true);
                "its len is zero again":
                    env: {42}
                    before_each
                    env: {}
                    assert_eq!(env.set.len(), 0);
```

</details>

---

Due to the struct mutability isolation of my environment "sharing" implementation `_all` and `_each` in 9 out of 10 situations are equivalent. Like in the code above one could just as well have used `before_all` in the latter use. It would have been semantically equivalent to `before_each`, just a bit faster due to being called just once per parent-context, not once per sub-context. The only situation where there actually is a difference is when `env` contains shared mutable state behind an `Arc` or the like. So maybe we might want to simply name `before_all` and `after_all` `before` and `after` as they are what you'd want to use 9 out of 10 times anyway? 🤔 

---

On a broader scope, how should we proceed merging these changes onto master?
Should I create several PRs that build up onto each other? Like starting with "env", followed by "before_after", followed by "timing", followed by …?

**Comment by mackwic** [comment]
Yes I am totally ok to name `before_all` => `before` and `after_all` => `after`. But I'd like to keep the `_all` variant when explicitness is required.

By experience, mega PR are not great, but many depending PRs are even worse. Let's do a mega PR.

**Comment by regexident** [comment]
> Yes I am totally ok to name before_all => before and after_all => after. But I'd like to keep the _all variant when explicitness is required.

Sounds good to me.

> By experience, mega PR are not great, but many depending PRs are even worse. Let's do a mega PR.

Or we just do it one by one. I just happened to have worked on "before/after" alongside "environment" (which was somewhat necessary as a non-changing environment isn't doing much and many bugs I only found after adding "before/after").

The rest I haven't started yet, so having non-dependent clean PRs should work for the rest.

Lemme prepare a proper PR for "environment" + "before/after". Then let's discuss and merge it and proceed with the rest on a more granular basis.
